/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eaio_nativecall_NativeCall */

#ifndef _Included_com_eaio_nativecall_NativeCall
#define _Included_com_eaio_nativecall_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eaio_nativecall_NativeCall
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eaio_nativecall_NativeCall_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_eaio_nativecall_NativeCall
 * Method:    initHandles
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_eaio_nativecall_NativeCall_initHandles
  (JNIEnv *, jobject);

/*
 * Class:     com_eaio_nativecall_NativeCall
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eaio_nativecall_NativeCall_getLastError
  (JNIEnv *, jobject);

/*
 * Class:     com_eaio_nativecall_NativeCall
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eaio_nativecall_NativeCall_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
