/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eaio_nativecall_IntCall */

#ifndef _Included_com_eaio_nativecall_IntCall
#define _Included_com_eaio_nativecall_IntCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eaio_nativecall_IntCall
 * Method:    executeCall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_eaio_nativecall_IntCall_executeCall
  (JNIEnv *, jobject);

/*
 * Class:     com_eaio_nativecall_IntCall
 * Method:    executeCall0
 * Signature: ([Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_eaio_nativecall_IntCall_executeCall0
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
