/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eaio_nativecall_VoidCall */

#ifndef _Included_com_eaio_nativecall_VoidCall
#define _Included_com_eaio_nativecall_VoidCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eaio_nativecall_VoidCall
 * Method:    executeCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eaio_nativecall_VoidCall_executeCall
  (JNIEnv *, jobject);

/*
 * Class:     com_eaio_nativecall_VoidCall
 * Method:    executeCall0
 * Signature: ([Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_eaio_nativecall_VoidCall_executeCall0
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
