######################################################################
# Automatically generated by qmake (2.01a) Sun May 31 15:49:45 2009
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwin.h goodwidget.h
SOURCES += main.cpp mainwin.cpp goodwidget.cpp
